# Generated by Django 4.1.2 on 2022-10-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_rename_name_tag_first_name_tag_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyric',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
