# Generated by Django 4.1.2 on 2022-10-27 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0006_tag2_lyric_tag2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lyric',
            name='tag2',
        ),
        migrations.AddField(
            model_name='lyric',
            name='artiste_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='musicapp.artiste'),
        ),
        migrations.AlterField(
            model_name='lyric',
            name='song_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='musicapp.song'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artiste_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='musicapp.artiste'),
        ),
        migrations.DeleteModel(
            name='Tag2',
        ),
    ]
