# Generated by Django 4.1.2 on 2022-10-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_tag_artiste_age_alter_artiste_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='tag',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
