# Generated by Django 4.1.2 on 2022-10-27 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0005_alter_lyric_song_id_alter_song_artiste_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artiste_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='musicapp.artiste')),
            ],
        ),
        migrations.AddField(
            model_name='lyric',
            name='tag2',
            field=models.ManyToManyField(to='musicapp.tag2'),
        ),
    ]
